import type { ChecklistSectionData } from './types';
import {
  Droplet,
  Thermometer,
  Settings2,
  Wind,
  Lightbulb,
  Disc3,
  CircleParking,
  View,
  Volume2,
  ShieldAlert,
  ArrowUpFromLine,
  Pipette,
  Link,
  Link2,
  LayoutGrid,
  ChevronsUpDown,
  Anchor,
  Shovel,
  Gamepad2,
  ShieldCheck,
  Wrench,
  Truck,
  Box,
  Construction,
} from 'lucide-react';

export const CHECKLIST_DATA: ChecklistSectionData[] = [
  {
    id: 'truck',
    name: 'Truck (2021 Chevy 6500)',
    Icon: Truck,
    items: [
      { id: 'truck-oil', name: 'Engine Oil Level', instructions: 'With engine off, check dipstick. Level must be between Add and Full marks.', Icon: Droplet },
      { id: 'truck-coolant', name: 'Coolant Level', instructions: 'Check coolant recovery tank fluid level. Must be between Min and Max.', Icon: Thermometer },
      { id: 'truck-brake-fluid', name: 'Brake Fluid Level', instructions: 'Visually inspect master cylinder reservoir. Level must be between Min and Max.', Icon: Droplet },
      { id: 'truck-power-steering', name: 'Power Steering Fluid', instructions: 'Check reservoir level. Must be within the operating range indicated on dipstick or reservoir.', Icon: Settings2 },
      { id: 'truck-washer-fluid', name: 'Windshield Washer Fluid', instructions: 'Visually check reservoir. Fill as needed to ensure visibility.', Icon: Wind },
      { id: 'truck-lights', name: 'Lights & Reflectors', instructions: 'Verify operation of all required lights: headlights (low/high), taillights, turn signals, brake lights, hazards, and clearance lights. Check for cleanliness and damage.', Icon: Lightbulb },
      { id: 'truck-tires', name: 'Tires', instructions: 'Check for proper inflation, cuts, bulges, and adequate tread depth (at least 4/32-inch on steer tires, 2/32-inch on others).', Icon: Disc3 },
      { id: 'truck-brakes', name: 'Brakes (Parking, Service)', instructions: 'Test parking brake for holding. For service brakes, check for pulling, unusual noises, or pedal issues.', Icon: CircleParking },
      { id: 'truck-mirrors', name: 'Mirrors', instructions: 'Mirrors must be clean, properly adjusted, and free of cracks or damage.', Icon: View },
      { id: 'truck-horn', name: 'Horn', instructions: 'Audibly test horn to ensure it is functional.', Icon: Volume2 },
      { id: 'truck-wipers', name: 'Wipers & Washers', instructions: 'Verify wiper blades are not damaged and operate smoothly. Test washer fluid spray.', Icon: Wind },
      { id: 'truck-safety-equip', name: 'Safety Equipment', instructions: 'Confirm fire extinguisher is charged and accessible, and reflective triangles are present and intact.', Icon: ShieldAlert },
      { id: 'truck-dump-bed', name: 'Dump Bed Operation', instructions: 'Check for hydraulic leaks. Ensure bed is fully down and secured. Verify PTO and controls are functional.', Icon: ArrowUpFromLine },
      { id: 'truck-leaks', name: 'Leaks (General)', instructions: 'Visually inspect under the vehicle for any signs of fuel, oil, coolant, or other fluid leaks.', Icon: Pipette },
      { id: 'truck-hitch', name: 'Fifth Wheel/Hitch', instructions: 'Check for secure mounting, cracks, or damage. Ensure jaw is locked and lubricated.', Icon: Link },
    ],
  },
  {
    id: 'trailer',
    name: 'Trailer (Tilt Deck)',
    Icon: Box,
    items: [
      { id: 'trailer-lights', name: 'Lights & Reflectors', instructions: 'Verify operation of all required lights and ensure reflectors are clean and intact.', Icon: Lightbulb },
      { id: 'trailer-tires', name: 'Tires', instructions: 'Check for proper inflation, cuts, bulges, and adequate tread depth (at least 2/32-inch).', Icon: Disc3 },
      { id: 'trailer-brakes', name: 'Brakes', instructions: 'Check brake lines for damage. If applicable, test electric or air brake operation.', Icon: CircleParking },
      { id: 'trailer-hitch-conn', name: 'Hitch & Landing Gear', instructions: 'Ensure coupling is secure and locked. Check landing gear is raised and handle is secured.', Icon: Link2 },
      { id: 'trailer-safety-chains', name: 'Safety Chains & Cables', instructions: 'Ensure chains/cables are properly attached, not twisted, and free from damage.', Icon: Link },
      { id: 'trailer-deck-cond', name: 'Deck Condition', instructions: 'Inspect flooring for damage, holes, or weakness. Ensure it is clear of debris.', Icon: LayoutGrid },
      { id: 'trailer-tilt-mech', name: 'Tilt Mechanism', instructions: 'Inspect hydraulic system for leaks. Ensure pivot points are secure and lubricated.', Icon: ChevronsUpDown },
      { id: 'trailer-load-secure', name: 'Load Securement Points', instructions: 'Check all D-rings, stake pockets, and rub rails for damage or cracks.', Icon: Anchor },
    ],
  },
  {
    id: 'skidSteer',
    name: 'Skid Steer',
    Icon: Construction,
    items: [
      { id: 'skid-fluids', name: 'Fluid Levels', instructions: 'Check engine oil, hydraulic oil, and coolant levels. Ensure they are within operating range.', Icon: Droplet },
      { id: 'skid-lights', name: 'Lights & Alarms', instructions: 'Test all work lights and audible alarms (like backup alarms) for proper function.', Icon: Lightbulb },
      { id: 'skid-tires-tracks', name: 'Tires / Tracks', instructions: 'Check tires for damage and proper inflation, or tracks for proper tension and signs of wear.', Icon: Disc3 },
      { id: 'skid-bucket-attach', name: 'Bucket / Attachment', instructions: 'Inspect for damage, excessive wear, and secure connection via locking pins.', Icon: Shovel },
      { id: 'skid-controls', name: 'Controls & Hydraulics', instructions: 'Cycle all controls to ensure smooth operation. Check hoses for leaks or damage.', Icon: Gamepad2 },
      { id: 'skid-safety-feat', name: 'Safety Features', instructions: 'Check seatbelt, safety bar, and ROPS (Rollover Protective Structure) for damage.', Icon: ShieldCheck },
      { id: 'skid-leaks', name: 'Leaks (General)', instructions: 'Visually inspect under and around the machine for any signs of fluid leaks.', Icon: Pipette },
      { id: 'skid-grease', name: 'Grease Points', instructions: "Inspect all pivot points and grease as needed according to the manufacturer's schedule.", Icon: Wrench },
    ],
  },
];
